project:
  type: website
  output-dir: docs # El nombre que espera GitHub Pages
  execute-dir: project # Para no tener que usar here::here()

website:
  title: "R en Vivo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

lang: es
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



