project:
  type: website
  output-dir: docs # El nombre que espera GitHub Pages
  execute-dir: project # Para no tener que usar here::here()

website:
  title: "R en Vivo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - sidebar:documentos
      - href: dashboard.qmd
        text: Dashboard
      - href: presentaciones.qmd
        text: Presentaciones
      - href: about.qmd
        text: Acerca de
  sidebar:
    - id: documentos
      title: Documentos
      style: docked
      contents:
        - documentos/memoria-de-calculo.qmd
        - documentos/reporte.qmd

lang: es
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



